### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by alexander-potemkin** [jitsi-contrib/installers#1]
Thank you for the script! How do I upgrade my Jitsi instance once I installed it with this script?

**Comment by emrahcom** [comment]
Sorry for the late response. I just saw the message.

There is no difference than manually installed Jitsi

```bash
apt-get update
apt-get dist-upgrade
```

But I always prefere to reinstall the whole system using the same script if I don't have much customizations

**Comment by alexander-potemkin** [comment]
@emrahcom , no problems and thanks for coming back!

I appreciate the script you did a lot, it's just a huge time saver!

Thank you, got it! From your experience, does it work ok with unattended-upgrades or automatic `apt upgrade`? Just to cover recent security issues?

**Comment by emrahcom** [comment]
I never use automatic updates. It may be used for desktop machines but it's very risky for servers in my opinion. I always do manual upgrades.

**Comment by alexander-potemkin** [comment]
Right. I'm with you, but I turned on automatic security upgrades and do manual `sudo apt upgrade` every now and then.
So far the Jitsi server survived it and if it won't, I guess I will reinstall it on the clean machine.

Thanks again for the script!
