### ISSUE TITLE
Jitsi-Jibri installtion

### ISSUE THREAD

**Issue by deepaksharma9899** [jitsi-contrib/installers#4]
Hello Friend,

Thanks for developing these scripts.
When I tried to run jitsi-jibri script on aws c5.2xlarge(16gb ram, 8 cpu, 95gb storage) ubuntu 20.4 OS, it installed succesfully. But when i tried to record the meeting, recording has started and after 3-4 sec it got failed. Can you please tell me the reason behind this.

**Comment by emrahcom** [comment]
Can you share the logs which are in `/var/log/jitsi/jibri/` folder?

You may also continue this topic in [the community forum](https://community.jitsi.org/)

**Comment by deepaksharma9899** [comment]
}, {
   "level": "SEVERE",
   "message": "https://meet.theworkpc.com/libs/app.bundle.min.js?v=7499 1:1118334 \"2023-09-12T08:19:25.915Z\" \"[features/base/tracks]\" \"Failed to create local tracks\" Array(1) qt",
   "source": "console-api",
   "timestamp": 1.694506765915e+12
}, {
   "level": "SEVERE",
   "message": "https://meet.theworkpc.com/libs/app.bundle.min.js?v=7499 1:1118334 \"2023-09-12T08:19:25.915Z\" \"[conference.js]\" \"Audio track creation failed with error gum.general: Could not start audio source\"",
   "source": "console-api",
   "timestamp": 1.694506765915e+12
}, {
   "level": "WARNING",
   "message": "https://meet.theworkpc.com/libs/lib-jitsi-meet.min.js?v=7499 1:34750 \"2023-09-12T08:19:26.496Z\" \"[modules/xmpp/XmppConnection.js]\" \"\\u003Cfo._mayb>
   "source": "console-api",
   "timestamp": 1.694506766497e+12
}, {
   "level": "WARNING",
   "message": "https://meet.theworkpc.com/libs/lib-jitsi-meet.min.js?v=7499 1:34750 \"2023-09-12T08:19:26.687Z\" \"[modules/recording/RecordingManager.js]\" \"\\u003CJ>
   "source": "console-api",
   "timestamp": 1.694506766687e+12
} ]

2023-09-12 08:19:32.068 INFO: [62] JibriSelenium.leaveCallAndQuitBrowser#350: [2023-09-12T08:19:31+0000] [INFO] [905726f48925b2a0f3c150a190a84b9c] COMMAND GetLog {
   "type": "driver"
}

2023-09-12 08:19:32.068 INFO: [62] JibriSelenium.leaveCallAndQuitBrowser#350: [2023-09-12T08:19:31+0000] [FINE] DevTools WebSocket Command: Runtime.evaluate (id=111) (>
   "awaitPromise": false,
   "expression": "1",
   "returnByValue": true
}

2023-09-12 08:19:32.068 INFO: [62] JibriSelenium.leaveCallAndQuitBrowser#350: [2023-09-12T08:19:31+0000] [FINE] DevTools WebSocket Response: Runtime.evaluate (id=111) >
   "result": {
      "description": "1",
      "type": "number",
      "value": 1
   }
}

> Can you share the logs which are in `/var/log/jitsi/jibri/` folder?
> 
> You may also continue this topic in [the community forum](https://community.jitsi.org/)

**Comment by deepaksharma9899** [comment]
Hey, I pasted the logs. Please see it.

**Comment by emrahcom** [comment]
Sharing a few lines from log doesn't help. Please share all logs in the community forum by using a readable format.

**Comment by emrahcom** [comment]
Solved in the community forum.

The problem was that there was already a desktop environment on the server. So `jibri` cannot enable its own desktop.
